version: '3'
services:
  janus:
    build:
      context: ./janus
      dockerfile: Dockerfile
    ports:
      - '8188:8188'
      - '8088:8088'
      - '8089:8089'
      - '8889:8889'
      - '8000:8000'
      - '7088:7088'
      - '7089:7089'
    volumes:
      - "./janus/etc/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./janus/etc/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
      - "./janus/etc/janus/janus.plugin.streaming.jcfg:/usr/local/etc/janus/janus.plugin.streaming.jcfg"
      - "./janus/etc/janus/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg"
      - "./janus/etc/janus/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg"
  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./vue:/build"
